package io.github.vlaaad.ghostty;

/// Physical key codes (complete list).
public enum Key {
    UNIDENTIFIED,
    
    // Writing System Keys (W3C § 3.1.1)
    BACKQUOTE, BACKSLASH, BRACKET_LEFT, BRACKET_RIGHT, COMMA,
    DIGIT_0, DIGIT_1, DIGIT_2, DIGIT_3, DIGIT_4, DIGIT_5, DIGIT_6, DIGIT_7, DIGIT_8, DIGIT_9,
    EQUAL, INTL_BACKSLASH, INTL_RO, INTL_YEN,
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    MINUS, PERIOD, QUOTE, SEMICOLON, SLASH,
    
    // Functional Keys (W3C § 3.1.2)
    ALT_LEFT, ALT_RIGHT, BACKSPACE, CAPS_LOCK, CONTEXT_MENU,
    CONTROL_LEFT, CONTROL_RIGHT, ENTER, META_LEFT, META_RIGHT,
    SHIFT_LEFT, SHIFT_RIGHT, SPACE, TAB,
    CONVERT, KANA_MODE, NON_CONVERT,
    
    // Control Pad Section (W3C § 3.2)
    DELETE, END, HELP, HOME, INSERT, PAGE_DOWN, PAGE_UP,
    
    // Arrow Pad Section (W3C § 3.3)
    ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP,
    
    // Numpad Section (W3C § 3.4)
    NUM_LOCK, NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5, NUMPAD_6, NUMPAD_7, NUMPAD_8, NUMPAD_9,
    NUMPAD_ADD, NUMPAD_BACKSPACE, NUMPAD_CLEAR, NUMPAD_CLEAR_ENTRY, NUMPAD_COMMA, NUMPAD_DECIMAL, NUMPAD_DIVIDE,
    NUMPAD_ENTER, NUMPAD_EQUAL, NUMPAD_MEMORY_ADD, NUMPAD_MEMORY_CLEAR, NUMPAD_MEMORY_RECALL, NUMPAD_MEMORY_STORE,
    NUMPAD_MEMORY_SUBTRACT, NUMPAD_MULTIPLY, NUMPAD_PAREN_LEFT, NUMPAD_PAREN_RIGHT, NUMPAD_SUBTRACT,
    NUMPAD_SEPARATOR, NUMPAD_UP, NUMPAD_DOWN, NUMPAD_RIGHT, NUMPAD_LEFT, NUMPAD_BEGIN, NUMPAD_HOME, NUMPAD_END,
    NUMPAD_INSERT, NUMPAD_DELETE, NUMPAD_PAGE_UP, NUMPAD_PAGE_DOWN,
    
    // Function Section (W3C § 3.5)
    ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20,
    F21, F22, F23, F24, F25, FN, FN_LOCK, PRINT_SCREEN, SCROLL_LOCK, PAUSE,
    
    // Media Keys (W3C § 3.6)
    BROWSER_BACK, BROWSER_FAVORITES, BROWSER_FORWARD, BROWSER_HOME, BROWSER_REFRESH, BROWSER_SEARCH, BROWSER_STOP,
    EJECT, LAUNCH_APP_1, LAUNCH_APP_2, LAUNCH_MAIL,
    MEDIA_PLAY_PAUSE, MEDIA_SELECT, MEDIA_STOP, MEDIA_TRACK_NEXT, MEDIA_TRACK_PREVIOUS,
    POWER, SLEEP, AUDIO_VOLUME_DOWN, AUDIO_VOLUME_MUTE, AUDIO_VOLUME_UP, WAKE_UP,
    
    // Legacy, Non-standard, and Special Keys (W3C § 3.7)
    COPY, CUT, PASTE
}
